import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
// import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
// import { AppSidebar } from "./comp/sidebar";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "./comp/Navbar";
import { ThemeProvider } from "./comp/theme-provider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const roboto = Roboto({
    variable: "--font-roboto",
    subsets: ["latin"],
    weight:["100","300","400","500","700","900"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={` ${roboto.variable} antialiased`}>
                <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                    {/* <SidebarProvider>
                        <AppSidebar /> */}
                        {/* <SidebarTrigger /> */}
                        <main className="w-full">
                            <Navbar />
                            {children}
                        </main>
                        <Toaster />
                    {/* </SidebarProvider> */}
                </ThemeProvider>
            </body>
        </html>
    );
}
